function final_research_dashboard(cases,mc,analysis,cfg)
%FINAL_RESEARCH_DASHBOARD Automatic end-of-experiment summary figure.
if ~isfield(cfg,'saveFigures'), cfg.saveFigures=true; end
names={'PID','Fixed LQR','GS-LQR','MPC'}; mpc=cases{4}.metrics;
fig=figure('Color','w','Name','Final Research Summary','Position',[80 60 1120 760]);
subplot(2,2,1);axis off;
text(0,1.00,'AUTONOMOUS NONLINEAR DRIFT CONTROL','FontSize',16,'FontWeight','bold','VerticalAlignment','top');
text(0,0.89,'Master''s Control Systems Engineering - Experiment Summary','FontSize',11,'FontWeight','bold');
lines={...
    'Plant: nonlinear 4-wheel RWD + Fiala tyres + friction ellipse',...
    'Estimator: Extended Kalman Filter (EKF)',...
    'Controllers: PID / Fixed LQR / Gain-Scheduled LQR / Constrained MPC',...
    sprintf('Controllability: %d/5    Observability: %d/5',analysis.rankControllability,analysis.rankObservability),...
    sprintf('Monte Carlo: %d runs    Success: %.1f%%',numel(mc.success),mc.successRate),...
    sprintf('MPC beta RMSE: %.3f deg    Path RMSE: %.3f m',mpc.betaRMSEdeg,mpc.pathRMSE),...
    sprintf('MPC yaw RMSE: %.3f deg/s   Speed RMSE: %.3f km/h',mpc.yawRMSEdeg,mpc.speedRMSEkmh),...
    sprintf('MPC mean compute: %.3f ms  Max: %.3f ms',mpc.meanComputeMs,mpc.maxComputeMs),...
    sprintf('EKF yaw RMSE: raw %.3f -> estimated %.3f deg/s',mpc.rawYawRMSEdeg,mpc.ekfYawRMSEdeg),...
    sprintf('EKF speed RMSE: raw %.3f -> estimated %.3f m/s',mpc.rawSpeedRMSE,mpc.ekfSpeedRMSE)};
for i=1:numel(lines),text(0,0.80-(i-1)*0.075,lines{i},'FontSize',9.5);end

subplot(2,2,2);vals=zeros(4,2);for i=1:4,vals(i,:)=[cases{i}.metrics.betaRMSEdeg cases{i}.metrics.pathRMSE];end
bar(vals);grid on;set(gca,'XTick',1:4,'XTickLabel',names);ylabel('RMSE');legend('\beta (deg)','Path (m)','Location','best');title('Controller tracking comparison');

subplot(2,2,3);plot(cases{4}.t,rad2deg(cases{4}.beta),'LineWidth',1.1);hold on;plot(cases{4}.t,rad2deg(cases{4}.ref.beta),'k--','LineWidth',1.1);grid on;xlabel('Time (s)');ylabel('\beta (deg)');legend('MPC actual','Reference','Location','best');title('Constrained MPC sideslip tracking');

subplot(2,2,4);histogram(mc.betaRMSEdeg,max(10,round(sqrt(numel(mc.betaRMSEdeg)))));grid on;xlabel('\beta RMSE (deg)');ylabel('Runs');title(sprintf('Robustness distribution - %.1f%% success',mc.successRate));

if cfg.saveFigures, exportgraphics(fig,fullfile(cfg.outputDir,'research_final_summary.png'),'Resolution',180); end
end
